// <auto-generated />
using Final;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final.TeamClass", b =>
                {
                    b.Property<int>("TeamClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("TeamNameId")
                        .HasColumnType("int");

                    b.Property<string>("YearStarted")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            TeamClassId = 1,
                            ClassName = "Contemperary Programming",
                            Grade = 100,
                            TeamNameId = 1,
                            YearStarted = "5/8/2022"
                        },
                        new
                        {
                            TeamClassId = 2,
                            ClassName = "Contemperary Programming",
                            Grade = 100,
                            TeamNameId = 2,
                            YearStarted = "5/8/2022"
                        },
                        new
                        {
                            TeamClassId = 3,
                            ClassName = "Contemperary Programming",
                            Grade = 100,
                            TeamNameId = 3,
                            YearStarted = "5/8/2022"
                        });
                });

            modelBuilder.Entity("Final.TeamGame", b =>
                {
                    b.Property<int>("TeamGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNameId")
                        .HasColumnType("int");

                    b.Property<string>("YearStarted")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamGameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            TeamGameId = 1,
                            Frequency = "4/month",
                            GameName = "Call of Duty Black Ops 2",
                            TeamNameId = 1,
                            YearStarted = "5/8/2022"
                        },
                        new
                        {
                            TeamGameId = 2,
                            Frequency = "12/month",
                            GameName = "Minecraft",
                            TeamNameId = 2,
                            YearStarted = "5/8/2022"
                        },
                        new
                        {
                            TeamGameId = 3,
                            Frequency = "8/month",
                            GameName = "Far Cry 3",
                            TeamNameId = 3,
                            YearStarted = "5/8/2022"
                        });
                });

            modelBuilder.Entity("Final.TeamHobby", b =>
                {
                    b.Property<int>("TeamHobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNameId")
                        .HasColumnType("int");

                    b.Property<string>("YearStarted")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamHobbyId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            TeamHobbyId = 1,
                            Frequency = "4/Month",
                            HobbyName = "Martial Art",
                            Location = "Fairfield",
                            TeamNameId = 1,
                            YearStarted = "04/04/1999"
                        },
                        new
                        {
                            TeamHobbyId = 2,
                            Frequency = "8/Month",
                            HobbyName = "Guitar",
                            Location = "Home",
                            TeamNameId = 2,
                            YearStarted = "10/30/2009"
                        },
                        new
                        {
                            TeamHobbyId = 3,
                            Frequency = "8/Month",
                            HobbyName = "Hiking",
                            Location = "Park",
                            TeamNameId = 3,
                            YearStarted = "10/30/2009"
                        });
                });

            modelBuilder.Entity("Final.TeamName", b =>
                {
                    b.Property<int>("TeamNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamNameId");

                    b.ToTable("Names");

                    b.HasData(
                        new
                        {
                            TeamNameId = 1,
                            Birthate = "04/04/1995",
                            CollegeProgram = "Networking System",
                            FullName = "Guy-David Ngondo",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            TeamNameId = 2,
                            Birthate = "02/20/2000",
                            CollegeProgram = "Software Dev",
                            FullName = "Mitchell Hansbauer",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            TeamNameId = 3,
                            Birthate = "04/04/1990",
                            CollegeProgram = "Software Dev",
                            FullName = "Robert Champion",
                            YearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
